# Generated by Django 5.0.3 on 2024-03-31 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """ This file is used to create the initial model for the core app. """
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FibonacciResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter", models.PositiveIntegerField()),
                ("result", models.BigIntegerField()),
                (
                    "execution_time",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("date_launched", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fibonacci Result",
                "verbose_name_plural": "Fibonacci Results",
            },
        ),
    ]
