name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r ./back/requirements.txt
        


    - name: Check code formatting with Black
      run: |
        black --check .


    

    - name: Run pytest and coverage
      run: |
        pytest ./back
      
    - name: Run pytest with coverage
      run: |
        pytest ./back --cov=./back/core --cov-report=term --cov-fail-under=90
      

    - name: Lint with pylint
      run: |
        pylint --rcfile=./back/.pylintrc ./back/core
        pylint --rcfile=./back/.pylintrc ./back/api

    # Add additional steps for your build process as needed
    - name: Build
      run: echo "Add your build command here"