name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pylint black

    - name: Check code formatting with Black
      run: |
        black --check .

    - name: Lint with pylint
      run: |
        pylint 

    - name: Run pytest and coverage
      run: |
        pytest --cov=./ --cov-report=term --cov-fail-under=95

    # Add additional steps for your build process as needed
    - name: Build
      run: echo "Add your build command here"